export { CrossIcon } from './Cross'
export { FunnelIcon } from './Funnel'
export { MagnifyingGlassIcon } from './MagnifyingGlass'
export { InfoIcon } from './Info'
export { OpenDataIcon } from './OpenData'
export { SunIcon } from './Sun'
